runtime: nodejs20
service: google-campaign-leads-service

env_variables:
  NODE_ENV: production
  GOOGLE_SERVICE_ACCOUNT_KEY: ${DEPLOY_GAE_SA}

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10


handlers:
- url: /.*
  script: auto

entrypoint: npm start