name: Deploy to App Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests (if available)
      run: |
        if npm run test --silent 2>/dev/null; then
          npm test
        else
          echo "No test script found, skipping tests"
        fi
      continue-on-error: false
      
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.DEPLOY_GAE_SA }}
        
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Verify authentication
      run: gcloud auth list
      
    - name: Deploy to App Engine
      run: |
        gcloud app deploy --quiet --promote
      env:
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.DEPLOY_GAE_SA }}
        
    - name: Get deployment URL
      run: |
        echo "Deployment URL: $(gcloud app browse --no-launch-browser)"
        
    - name: Health check
      run: |
        sleep 30
        HEALTH_URL="$(gcloud app browse --no-launch-browser)/health"
        echo "Checking health at: $HEALTH_URL"
        curl -f "$HEALTH_URL" || exit 1